### ISSUE TITLE
Registering on Boxeed In

### ISSUE THREAD

**Issue by lnp00** [cigamit/boxeehack#31]
I've tried to register on Boxeed In from two different IP subnets and i keep getting a message that my IP address has been blacklisted.  Anyone know what's going on?

TIA

**Comment by lnp00** [comment]
Make that three different IP subnets.  Something is wrong with your verification site, they are blacklisting every request.  How can I register to post on the Forums?

Cheers!

**Comment by jceelen** [comment]
Same problem here! Who is managing the forums?

**Comment by cigamit** [comment]
I think I finally tracked down what was causing this.  One of the blacklists was returning lots of false positives, so I have removed it completely.

**Comment by lnp00** [comment]
Yup, that did it; all registered now.  Thanks cigamit!
