### ISSUE TITLE
BoxeeHacks 1.6 issues

### ISSUE THREAD

**Issue by quasar1** [cigamit/boxeehack#32]
Great work for getting this out quick after the XBMC rebranding changes.

I just upgraded to BoxeeHacks 1.6 from 1.54 (which was modified for the XBMC to Kodi rebrand), and I am now having some issues .
I'm running from a mounted NAS NFS share and it boots into Boxee GUI first then loads Kodi.

@cigamit Is there something I can tweak in the files to fix the issue?

If not is there an easy way to downgrade to 1.54 again?

Thanks.

**Comment by cigamit** [comment]
Hmmm.  It is most likely a timing issue.  Boxee is loading faster than the initialization scripts.  If you telnet in, unmount your NAS, then run the script for mounting it again, is it taking a while to properly connect and mount it?

**Comment by quasar1** [comment]
I did the ```umount -f ``` command to forcibly unmount and when I tried to re-mount  it came back with:
```mount: RPC: Timed out```
Not sure whats going on here, I will try rebooting the NAS...

**Comment by quasar1** [comment]
I just checked the network configuration of the NAS and noticed some log alerts about the DNS server address giving issues, I have fixed that and now it boots straight into Kodi.

Thanks for your help, I'll leave you to close this.

**Comment by cigamit** [comment]
NP, I really am thinking about creating a log that outputs the results from every init.d so that you know what is going on pretty quickly.
