### ISSUE TITLE
need help to watch movies

### ISSUE THREAD

**Issue by Allando2000** [cigamit/boxeehack#35]
Hi there

I have just pulled out my old boxee box and wanted to set it up in my daughters room for watching movies.

however i cant get it to Work. 

i tried installing the boxeeplus hack thing and think it is working, however i cant find any movies.
which app do i need to install or what can you recommen this old fart to do in order to get it to Work?

hope someone can help me out, so we can her started and Watch movies to improve her English.

**Comment by cigamit** [comment]
Please use the forums, this is not a help forum, but for issues with the code.
